### ISSUE TITLE
Can you add windowSize(width,  heigth)

### ISSUE THREAD

**Issue by RobTillaart** [TilenS6/ArduinoSerialDraw-Library#1]
Hi, 
interesting library and concept to draw on a virtual screen.
Could you add a command e.g. windowSize() to set the window size to draw in.
Think width and height should be 16 bit so it would allow to have a virtual screen of 1000 x 1000 or even more.

It could also be defined as the parameter of a begin(width, heigth) function.

**Comment by TilenS6** [comment]
@RobTillaart  We (developers) already talked about it and this feature will be coming very soon.

**Comment by chocoearly44** [comment]
Hi,
we appreciate your dedication to this library. We have just released version 1.0.1 which adds support for a number of pixels vertically and horizontally. We can't add support for window size because it's generated on the fly, so it's why the window is always the same size.

Thank you again,
JurijTSL
